### ISSUE TITLE
Can you add a license to the workflow directory?

### ISSUE THREAD

**Issue by aaomidi** [martinthomson/internet-draft-template#10]
Technically since the workflows are code, as it currently stands this is effectively not licensed for others to use. `apache2` would be the easiest for others to adopt. Thanks!

**Comment by martinthomson** [comment]
Sure.  Most of the code here is a direct copy from [i-d-template](https://github.com/martinthomson/i-d-template), which already has a [license](https://github.com/martinthomson/i-d-template/blob/main/LICENSE.md).  You can use that license.

I will have to look into a process for ensuring that any license I put in this repository doesn't end up in the repositories people create, because I don't want to accidentally have people put their work in the public domain in the same way.  They can have the code---part of the reason for the choice of public domain was so avoid any conflict in how the code is used when copied into other people's work---but I don't want to have the license leaking.  I might be able to place a license file and overwrite it during setup, but I need to ensure that process works reliably.
