### ISSUE TITLE
Submission fails; wrong email address used?

### ISSUE THREAD

**Issue by larseggert** [martinthomson/internet-draft-template#9]
Looking at https://github.com/NTAP/rfc8312bis/runs/6651625907?check_suite_focus=true, I think the submission fails, because the submission is tried with email address `xu@unl.edu`, which is not mine and does apparently not exist in the datatracker.

**Comment by martinthomson** [comment]
Yes, that seems like a good theory.

The API takes just one email address, so one is picked:

If you tag with `git tag -a`, then the email of the person who creates the tag is used.

If you tag with `git tag` or a GitHub release, the tag isn't annotated with an author, so the email address of the first author is picked.

The Datatracker API exists and could be queried based on the author name to see if the person exists, but the public API doesn't expose email addresses, so if I used that, it would only tell me if an account maybe exists under the author's name.  I could use that to skip authors who obviously don't have accounts, I guess.

**Comment by larseggert** [comment]
Yes, this was with a GitHub release, which I didn't do before (I used the shell).

You could also cycle through all author emails until one succeeds.

**Comment by martinthomson** [comment]
The number of ways in which submissions might fail are too numerous to use failure as a signal to try a different author.  Picking the wrong author email is low on the list of potential failure reasons.  (In the past, failures have generally been due to datatracker flakiness, but things have improved enough lately that I can't say what might go wrong.)

I might just need to provide a means to overwrite the guesswork in the Makefile.  It's fairly easy to set a variable indicating who is responsible for the submission.
